import { Popover, Transition } from '@headlessui/react'
import { ChevronDownIcon } from '@heroicons/react/solid'
import Head from 'next/head'
import Image from 'next/image'
import {Fragment} from 'react'
import Nav from '../components/nav'
import Footer from '../components/footer'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>veDao Clone</title>
        <meta name="clone of veDAO" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className="bg-gray-50 py-5 px-5 h-full pt-12">
        <div className="relative px-4 sm:px-6 lg:px-8">
          <div className="text-lg max-w-prose mx-auto">
            <h1>
              <span className="block text-base text-center text-red-500 font-semibold tracking-wide uppercase">
                Token Name
              </span>
              <span className="mt-2 block text-3xl text-center leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
              The people deserve a distro!
              </span>
            </h1>
            <p className="mt-8 text-xl text-center text-gray-500 leading-8">
            With governance choosing to pass VIP-5, veDAO has now entered a partnership with Solidex to assist in managing the Solidly veNFT. The community can earn $SOLID and $SEX rewards by depositing their USDC-WEVE LP tokens into Solidex. Tune into the veDAO Discord group and governance forum to stay up to date!
            </p>
          </div>
        </div>
        <div className="mx-auto max-w-screen-md mt-10">
          <dl className="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2">
            <div className="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
              <dt className="text-sm font-medium text-gray-500 truncate">Current Price</dt>
              <dd className="mt-1 text-3xl font-semibold text-gray-900">$1.00</dd>
            </div>
            <div className="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
              <dt className="text-sm font-medium text-gray-500 truncate">Liquidity</dt>
              <dd className="mt-1 text-3xl font-semibold text-gray-900">$123,453</dd>
            </div>
            <div className="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
              <dt className="text-sm font-medium text-gray-500 truncate">Market Cap</dt>
              <dd className="mt-1 text-3xl font-semibold text-gray-900">$434,434</dd>
            </div>
            <div className="px-4 py-5 bg-white shadow rounded-lg overflow-hidden sm:p-6">
              <dt className="text-sm font-medium text-gray-500 truncate">Fully Diluted Valuation</dt>
              <dd className="mt-1 text-3xl font-semibold text-gray-900">$29,281,213</dd>
            </div>
          </dl>
        </div>
      </div>
      <Footer />



    </div>
  )
}
